id: PFDD6E5FC
initial_creation_type: ocr
source_metadata:
  volumes:
    dfc9cd3179b2497a90f48006f6bdc075:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དེ་བཞིན་གཤེགས་པ་བརྒྱད་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
